library(ISLR)
library(leaps)
View(Hitters)
names(Hitters)
sum(is.na(Hitters$Salary))
Hitters=na.omit(Hitters)
dim(Hitters)

regfit.fwd = regsubsets(Salary~.,Hitters,nvmax=19,method="forward")
summary(regfit.fwd)
regfit.bwd = regsubsets(Salary~.,Hitters,nvmax=19,method="backward")
summary(regfit.bwd)
coef(regfit.full ,7)
coef(regfit.fwd ,7)
coef(regfit.bwd ,7)
plot(regfit.fwd,scale="bic")
plot(regfit.bwd,scale="bic")
